# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:4.0.3 SWIFT_SNAPSHOT=4.0.3 CUSTOM_TEST_SCRIPT=.kitura-test.sh DOCKER_PRIVILEGED=true
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:4.1.3 SWIFT_SNAPSHOT=4.1.3 CUSTOM_TEST_SCRIPT=.kitura-test.sh DOCKER_PRIVILEGED=true
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:4.2.3 SWIFT_TEST_ARGS="--parallel" DOCKER_PRIVILEGED=true
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=swift:4.2.3 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT DOCKER_PRIVILEGED=true
    - os: linux
      dist: xenial
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:18.04 SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT DOCKER_PRIVILEGED=true
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT JAZZY_ELIGIBLE=true SWIFT_TEST_ARGS="--parallel"
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
